source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Q_Example', :exclusive => true do
  pod 'Q', :path => '../'
end

target 'Q_Tests', :exclusive => true do
  pod 'Q', :path => '../'

  
end
